# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='no found doc')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('week_num', models.IntegerField(default=0)),
                ('user_name', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
