# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='doc',
            name='week_num',
            field=models.IntegerField(default=0),
        ),
    ]
