# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-01 03:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fourbox', '0002_auto_20170228_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='Staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
